2021-04-26 08:22:57.846 +02:00 [INF] Please setup your database in order to have the RabbitMq messaging backup feature
2021-04-26 08:22:58.654 +02:00 [INF] Please setup your database in order to have the RabbitMq messaging backup feature
2021-04-26 08:23:03.859 +02:00 [DBG] Hosting starting
2021-04-26 08:23:04.086 +02:00 [INF] User profile is available. Using 'C:\Users\apenahig\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2021-04-26 08:23:04.538 +02:00 [DBG] Reading data from file 'C:\Users\apenahig\AppData\Local\ASP.NET\DataProtection-Keys\key-9d073722-32c1-4422-88d8-684df3278e92.xml'.
2021-04-26 08:23:04.668 +02:00 [DBG] Found key {9d073722-32c1-4422-88d8-684df3278e92}.
2021-04-26 08:23:04.717 +02:00 [DBG] Considering key {9d073722-32c1-4422-88d8-684df3278e92} with expiration date 2021-06-21 11:20:35Z as default key.
2021-04-26 08:23:04.753 +02:00 [DBG] Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.13.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
2021-04-26 08:23:04.786 +02:00 [DBG] Decrypting secret element using Windows DPAPI.
2021-04-26 08:23:04.799 +02:00 [DBG] Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.13.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
2021-04-26 08:23:04.823 +02:00 [DBG] Opening CNG algorithm 'AES' from provider 'null' with chaining mode CBC.
2021-04-26 08:23:04.843 +02:00 [DBG] Opening CNG algorithm 'SHA256' from provider 'null' with HMAC.
2021-04-26 08:23:04.862 +02:00 [DBG] Using key {9d073722-32c1-4422-88d8-684df3278e92} as the default key.
2021-04-26 08:23:04.871 +02:00 [DBG] Key ring with default key {9d073722-32c1-4422-88d8-684df3278e92} was loaded during application startup.
2021-04-26 08:23:05.242 +02:00 [DBG] Registered model binder providers, in the following order: ["Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider"]
2021-04-26 08:23:05.347 +02:00 [DBG] Initializing Razor view compiler with no compiled views.
2021-04-26 08:23:05.515 +02:00 [DBG] Failed to locate the development https certificate at 'null'.
2021-04-26 08:23:05.533 +02:00 [WRN] Overriding address(es) 'https://localhost:8085'. Binding to endpoints defined in UseKestrel() instead.
2021-04-26 08:23:05.598 +02:00 [INF] Now listening on: https://0.0.0.0:8085
2021-04-26 08:23:05.605 +02:00 [DBG] Loaded hosting startup assembly Devon4Net.Application.WebAPI
2021-04-26 08:23:05.610 +02:00 [INF] Application started. Press Ctrl+C to shut down.
2021-04-26 08:23:05.616 +02:00 [INF] Hosting environment: Development
2021-04-26 08:23:05.618 +02:00 [INF] Content root path: C:\Users\apenahig\source\repos\Alejandria\source\Templates\WebAPI\Devon4Net.Application.WebAPI
2021-04-26 08:23:05.624 +02:00 [DBG] Hosting started
2021-04-26 08:23:05.917 +02:00 [DBG] Connection id "0HM88FF0DKGGP" received FIN.
2021-04-26 08:23:05.946 +02:00 [DBG] Connection id "0HM88FF0DKGGP" accepted.
2021-04-26 08:23:06.068 +02:00 [DBG] Connection id "0HM88FF0DKGGP" started.
2021-04-26 08:23:06.159 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:23:06.398 +02:00 [DBG] Connection id "0HM88FF0DKGGP" stopped.
2021-04-26 08:23:06.428 +02:00 [DBG] Connection id "0HM88FF0DKGGP" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:23:10.430 +02:00 [DBG] Connection id "0HM88FF0DKGGQ" accepted.
2021-04-26 08:23:11.785 +02:00 [DBG] Connection id "0HM88FF0DKGGQ" started.
2021-04-26 08:23:12.064 +02:00 [DBG] Connection id "0HM88FF0DKGGR" accepted.
2021-04-26 08:23:12.855 +02:00 [DBG] Connection id "0HM88FF0DKGGQ" received FIN.
2021-04-26 08:23:12.939 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:23:13.039 +02:00 [DBG] Connection id "0HM88FF0DKGGR" started.
2021-04-26 08:23:13.204 +02:00 [DBG] Connection id "0HM88FF0DKGGS" accepted.
2021-04-26 08:23:13.639 +02:00 [DBG] Connection id "0HM88FF0DKGGS" started.
2021-04-26 08:23:13.651 +02:00 [DBG] Connection id "0HM88FF0DKGGQ" stopped.
2021-04-26 08:23:13.875 +02:00 [DBG] Connection id "0HM88FF0DKGGR" received FIN.
2021-04-26 08:23:13.907 +02:00 [DBG] Connection id "0HM88FF0DKGGQ" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:23:13.939 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:23:14.219 +02:00 [DBG] Connection id "0HM88FF0DKGGT" accepted.
2021-04-26 08:23:14.469 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/index.html  
2021-04-26 08:23:15.005 +02:00 [DBG] Connection id "0HM88FF0DKGGR" stopped.
2021-04-26 08:23:15.224 +02:00 [DBG] Connection id "0HM88FF0DKGGT" started.
2021-04-26 08:23:15.303 +02:00 [DBG] Connection id "0HM88FF0DKGGR" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:23:15.344 +02:00 [DBG] Wildcard detected, all requests with hosts will be allowed.
2021-04-26 08:23:15.470 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:23:15.563 +02:00 [DBG] The request path /swagger/index.html does not match an existing file
2021-04-26 08:23:15.613 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:23:16.490 +02:00 [DBG] Connection id "0HM88FF0DKGGS" completed keep alive response.
2021-04-26 08:23:16.499 +02:00 [INF] Request finished in 2060.2375ms 200 text/html;charset=utf-8
2021-04-26 08:23:16.652 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/swagger-ui-bundle.js  
2021-04-26 08:23:16.668 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:23:16.671 +02:00 [DBG] The request path /swagger/swagger-ui-bundle.js does not match an existing file
2021-04-26 08:23:16.703 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:23:16.897 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/swagger-ui.css  
2021-04-26 08:23:16.911 +02:00 [DBG] Connection id "0HM88FF0DKGGU" accepted.
2021-04-26 08:23:17.082 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:23:17.090 +02:00 [DBG] Connection id "0HM88FF0DKGGU" started.
2021-04-26 08:23:17.092 +02:00 [DBG] The request path /swagger/swagger-ui.css does not match an existing file
2021-04-26 08:23:17.142 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:23:17.226 +02:00 [DBG] Connection id "0HM88FF0DKGGU" received FIN.
2021-04-26 08:23:17.281 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:23:17.536 +02:00 [DBG] Connection id "0HM88FF0DKGGV" accepted.
2021-04-26 08:23:17.524 +02:00 [INF] Sending file. Request path: '/swagger-ui.css'. Physical path: 'N/A'
2021-04-26 08:23:17.756 +02:00 [INF] Sending file. Request path: '/swagger-ui-bundle.js'. Physical path: 'N/A'
2021-04-26 08:23:18.108 +02:00 [DBG] Connection id "0HM88FF0DKGGU" stopped.
2021-04-26 08:23:18.108 +02:00 [DBG] Connection id "0HM88FF0DKGGV" started.
2021-04-26 08:23:18.122 +02:00 [DBG] Connection id "0HM88FF0DKGGS" completed keep alive response.
2021-04-26 08:23:18.122 +02:00 [DBG] Connection id "0HM88FF0DKGGT" completed keep alive response.
2021-04-26 08:23:18.137 +02:00 [DBG] Connection id "0HM88FF0DKGGU" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:23:18.193 +02:00 [INF] Request finished in 1303.7778ms 200 text/css
2021-04-26 08:23:18.201 +02:00 [INF] Request finished in 1559.4172ms 200 application/javascript
2021-04-26 08:23:18.218 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/swagger-ui-standalone-preset.js  
2021-04-26 08:23:18.239 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:23:18.244 +02:00 [DBG] The request path /swagger/swagger-ui-standalone-preset.js does not match an existing file
2021-04-26 08:23:18.260 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:23:18.387 +02:00 [INF] Sending file. Request path: '/swagger-ui-standalone-preset.js'. Physical path: 'N/A'
2021-04-26 08:23:18.392 +02:00 [DBG] Connection id "0HM88FF0DKGGS" completed keep alive response.
2021-04-26 08:23:18.422 +02:00 [INF] Request finished in 204.721ms 200 application/javascript
2021-04-26 08:23:18.651 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/v1/swagger.json  
2021-04-26 08:23:18.711 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:23:18.734 +02:00 [DBG] The request path /swagger/v1/swagger.json does not match an existing file
2021-04-26 08:23:18.778 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:23:21.406 +02:00 [DBG] Connection id "0HM88FF0DKGGS" completed keep alive response.
2021-04-26 08:23:21.410 +02:00 [INF] Request finished in 2776.3584ms 200 application/json;charset=utf-8
2021-04-26 08:23:22.691 +02:00 [DBG] Connection id "0HM88FF0DKGGT" received FIN.
2021-04-26 08:23:22.692 +02:00 [DBG] Connection id "0HM88FF0DKGGV" received FIN.
2021-04-26 08:23:22.692 +02:00 [DBG] Connection id "0HM88FF0DKGGS" received FIN.
2021-04-26 08:23:22.701 +02:00 [DBG] Connection id "0HM88FF0DKGGT" sending FIN because: "The client closed the connection."
2021-04-26 08:23:22.708 +02:00 [DBG] Connection id "0HM88FF0DKGGV" disconnecting.
2021-04-26 08:23:22.712 +02:00 [DBG] Connection id "0HM88FF0DKGGS" disconnecting.
2021-04-26 08:23:22.715 +02:00 [DBG] Connection id "0HM88FF0DKGGT" disconnecting.
2021-04-26 08:23:22.718 +02:00 [DBG] Connection id "0HM88FF0DKGGV" sending FIN because: "The client closed the connection."
2021-04-26 08:23:22.726 +02:00 [DBG] Connection id "0HM88FF0DKGGS" sending FIN because: "The client closed the connection."
2021-04-26 08:23:22.731 +02:00 [DBG] Connection id "0HM88FF0DKGGT" stopped.
2021-04-26 08:23:22.754 +02:00 [DBG] Connection id "0HM88FF0DKGGS" stopped.
2021-04-26 08:23:22.760 +02:00 [DBG] Connection id "0HM88FF0DKGGV" stopped.
2021-04-26 08:29:00.298 +02:00 [DBG] Connection id "0HM88FF0DKGH0" accepted.
2021-04-26 08:29:00.320 +02:00 [DBG] Connection id "0HM88FF0DKGH0" started.
2021-04-26 08:29:00.345 +02:00 [DBG] Connection id "0HM88FF0DKGH0" received FIN.
2021-04-26 08:29:00.350 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:29:00.438 +02:00 [DBG] Connection id "0HM88FF0DKGH0" stopped.
2021-04-26 08:29:00.465 +02:00 [DBG] Connection id "0HM88FF0DKGH0" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:29:00.538 +02:00 [DBG] Connection id "0HM88FF0DKGH1" accepted.
2021-04-26 08:29:00.570 +02:00 [DBG] Connection id "0HM88FF0DKGH1" started.
2021-04-26 08:29:00.598 +02:00 [DBG] Connection id "0HM88FF0DKGH1" received FIN.
2021-04-26 08:29:00.602 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:29:00.663 +02:00 [DBG] Connection id "0HM88FF0DKGH2" accepted.
2021-04-26 08:29:00.680 +02:00 [DBG] Connection id "0HM88FF0DKGH1" stopped.
2021-04-26 08:29:00.682 +02:00 [DBG] Connection id "0HM88FF0DKGH2" started.
2021-04-26 08:29:00.686 +02:00 [DBG] Connection id "0HM88FF0DKGH1" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:29:00.731 +02:00 [INF] Request starting HTTP/1.1 POST https://localhost:8085/v1/authormanagement/createuser?userId=Federico34&password=1234&role=author application/json 90
2021-04-26 08:29:00.745 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:29:00.750 +02:00 [DBG] POST requests are not supported
2021-04-26 08:29:00.767 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:29:00.779 +02:00 [DBG] POST requests are not supported
2021-04-26 08:29:00.836 +02:00 [DBG] No candidates found for the request path '/v1/authormanagement/createuser'
2021-04-26 08:29:00.842 +02:00 [DBG] Request did not match any endpoints
2021-04-26 08:29:00.931 +02:00 [DBG] Connection id "0HM88FF0DKGH3" accepted.
2021-04-26 08:29:00.939 +02:00 [DBG] Connection id "0HM88FF0DKGH3" started.
2021-04-26 08:29:01.082 +02:00 [DBG] AuthenticationScheme: Bearer was not authenticated.
2021-04-26 08:29:01.142 +02:00 [DBG] Request successfully matched the route with name 'null' and template 'v1/authormanagement/createuser'
2021-04-26 08:29:01.240 +02:00 [INF] Route matched with {action = "CreateUser", controller = "Author"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] CreateUser(System.String, System.String, System.String, Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto) on controller Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Controllers.AuthorController (Devon4Net.WebAPI.Implementation).
2021-04-26 08:29:01.248 +02:00 [DBG] Execution plan of authorization filters (in the following order): ["Microsoft.AspNetCore.Mvc.Cors.CorsAuthorizationFilter (Order: -2147483548)"]
2021-04-26 08:29:01.250 +02:00 [DBG] Execution plan of resource filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter"]
2021-04-26 08:29:01.254 +02:00 [DBG] Execution plan of action filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)","Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)"]
2021-04-26 08:29:01.263 +02:00 [DBG] Execution plan of exception filters (in the following order): ["None"]
2021-04-26 08:29:01.269 +02:00 [DBG] Execution plan of result filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter","Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)"]
2021-04-26 08:29:01.286 +02:00 [DBG] The request has an origin header: 'https://localhost:8085'.
2021-04-26 08:29:01.292 +02:00 [INF] CORS policy execution successful.
2021-04-26 08:29:01.297 +02:00 [DBG] Executing controller factory for controller Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Controllers.AuthorController (Devon4Net.WebAPI.Implementation)
2021-04-26 08:29:01.686 +02:00 [DBG] An 'IServiceProvider' was created for internal use by Entity Framework.
2021-04-26 08:44:58.164 +02:00 [INF] Please setup your database in order to have the RabbitMq messaging backup feature
2021-04-26 08:44:59.286 +02:00 [INF] Please setup your database in order to have the RabbitMq messaging backup feature
2021-04-26 08:45:04.913 +02:00 [DBG] Hosting starting
2021-04-26 08:45:05.226 +02:00 [INF] User profile is available. Using 'C:\Users\apenahig\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2021-04-26 08:45:05.850 +02:00 [DBG] Reading data from file 'C:\Users\apenahig\AppData\Local\ASP.NET\DataProtection-Keys\key-9d073722-32c1-4422-88d8-684df3278e92.xml'.
2021-04-26 08:45:05.917 +02:00 [DBG] Found key {9d073722-32c1-4422-88d8-684df3278e92}.
2021-04-26 08:45:05.954 +02:00 [DBG] Considering key {9d073722-32c1-4422-88d8-684df3278e92} with expiration date 2021-06-21 11:20:35Z as default key.
2021-04-26 08:45:05.998 +02:00 [DBG] Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.13.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
2021-04-26 08:45:06.031 +02:00 [DBG] Decrypting secret element using Windows DPAPI.
2021-04-26 08:45:06.044 +02:00 [DBG] Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.13.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
2021-04-26 08:45:06.066 +02:00 [DBG] Opening CNG algorithm 'AES' from provider 'null' with chaining mode CBC.
2021-04-26 08:45:06.084 +02:00 [DBG] Opening CNG algorithm 'SHA256' from provider 'null' with HMAC.
2021-04-26 08:45:06.101 +02:00 [DBG] Using key {9d073722-32c1-4422-88d8-684df3278e92} as the default key.
2021-04-26 08:45:06.108 +02:00 [DBG] Key ring with default key {9d073722-32c1-4422-88d8-684df3278e92} was loaded during application startup.
2021-04-26 08:45:06.351 +02:00 [DBG] Registered model binder providers, in the following order: ["Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider"]
2021-04-26 08:45:06.420 +02:00 [DBG] Initializing Razor view compiler with no compiled views.
2021-04-26 08:45:06.517 +02:00 [DBG] Failed to locate the development https certificate at 'null'.
2021-04-26 08:45:06.544 +02:00 [WRN] Overriding address(es) 'https://localhost:8085'. Binding to endpoints defined in UseKestrel() instead.
2021-04-26 08:45:06.693 +02:00 [INF] Now listening on: https://0.0.0.0:8085
2021-04-26 08:45:06.697 +02:00 [DBG] Loaded hosting startup assembly Devon4Net.Application.WebAPI
2021-04-26 08:45:06.701 +02:00 [INF] Application started. Press Ctrl+C to shut down.
2021-04-26 08:45:06.705 +02:00 [INF] Hosting environment: Development
2021-04-26 08:45:06.708 +02:00 [INF] Content root path: C:\Users\apenahig\source\repos\Alejandria\source\Templates\WebAPI\Devon4Net.Application.WebAPI
2021-04-26 08:45:06.729 +02:00 [DBG] Hosting started
2021-04-26 08:45:07.201 +02:00 [DBG] Connection id "0HM88FRA6B203" received FIN.
2021-04-26 08:45:07.202 +02:00 [DBG] Connection id "0HM88FRA6B203" accepted.
2021-04-26 08:45:07.205 +02:00 [DBG] Connection id "0HM88FRA6B203" started.
2021-04-26 08:45:07.237 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:45:07.398 +02:00 [DBG] Connection id "0HM88FRA6B203" stopped.
2021-04-26 08:45:07.461 +02:00 [DBG] Connection id "0HM88FRA6B203" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:45:11.173 +02:00 [DBG] Connection id "0HM88FRA6B204" accepted.
2021-04-26 08:45:11.194 +02:00 [DBG] Connection id "0HM88FRA6B204" started.
2021-04-26 08:45:11.565 +02:00 [DBG] Connection id "0HM88FRA6B205" accepted.
2021-04-26 08:45:11.576 +02:00 [DBG] Connection id "0HM88FRA6B205" started.
2021-04-26 08:45:11.896 +02:00 [DBG] Connection id "0HM88FRA6B204" received FIN.
2021-04-26 08:45:11.901 +02:00 [DBG] Connection id "0HM88FRA6B205" received FIN.
2021-04-26 08:45:11.925 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:45:11.925 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:45:11.949 +02:00 [DBG] Connection id "0HM88FRA6B205" stopped.
2021-04-26 08:45:11.981 +02:00 [DBG] Connection id "0HM88FRA6B204" stopped.
2021-04-26 08:45:11.991 +02:00 [DBG] Connection id "0HM88FRA6B205" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:45:12.008 +02:00 [DBG] Connection id "0HM88FRA6B204" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:45:12.217 +02:00 [DBG] Connection id "0HM88FRA6B206" accepted.
2021-04-26 08:45:12.227 +02:00 [DBG] Connection id "0HM88FRA6B206" started.
2021-04-26 08:45:12.435 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/index.html  
2021-04-26 08:45:12.463 +02:00 [DBG] Wildcard detected, all requests with hosts will be allowed.
2021-04-26 08:45:12.467 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:45:12.470 +02:00 [DBG] Connection id "0HM88FRA6B207" accepted.
2021-04-26 08:45:12.474 +02:00 [DBG] Connection id "0HM88FRA6B207" started.
2021-04-26 08:45:12.515 +02:00 [DBG] The request path /swagger/index.html does not match an existing file
2021-04-26 08:45:12.549 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:45:12.910 +02:00 [DBG] Connection id "0HM88FRA6B206" completed keep alive response.
2021-04-26 08:45:12.915 +02:00 [INF] Request finished in 495.4373ms 200 text/html;charset=utf-8
2021-04-26 08:45:13.005 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/swagger-ui-bundle.js  
2021-04-26 08:45:13.181 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:45:13.189 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/swagger-ui.css  
2021-04-26 08:45:13.208 +02:00 [DBG] The request path /swagger/swagger-ui-bundle.js does not match an existing file
2021-04-26 08:45:13.214 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:45:13.219 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:45:13.224 +02:00 [DBG] The request path /swagger/swagger-ui.css does not match an existing file
2021-04-26 08:45:13.233 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:45:13.301 +02:00 [DBG] Connection id "0HM88FRA6B208" accepted.
2021-04-26 08:45:13.339 +02:00 [DBG] Connection id "0HM88FRA6B208" started.
2021-04-26 08:45:13.409 +02:00 [DBG] Connection id "0HM88FRA6B208" received FIN.
2021-04-26 08:45:13.414 +02:00 [INF] Sending file. Request path: '/swagger-ui.css'. Physical path: 'N/A'
2021-04-26 08:45:13.422 +02:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2021-04-26 08:45:13.452 +02:00 [DBG] Connection id "0HM88FRA6B206" completed keep alive response.
2021-04-26 08:45:13.503 +02:00 [DBG] Connection id "0HM88FRA6B208" stopped.
2021-04-26 08:45:13.514 +02:00 [INF] Request finished in 325.3166ms 200 text/css
2021-04-26 08:45:13.522 +02:00 [DBG] Connection id "0HM88FRA6B208" sending FIN because: "The Socket transport's send loop completed gracefully."
2021-04-26 08:45:13.535 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/swagger-ui-standalone-preset.js  
2021-04-26 08:45:13.543 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:45:13.548 +02:00 [INF] Sending file. Request path: '/swagger-ui-bundle.js'. Physical path: 'N/A'
2021-04-26 08:45:13.551 +02:00 [DBG] The request path /swagger/swagger-ui-standalone-preset.js does not match an existing file
2021-04-26 08:45:13.559 +02:00 [DBG] Connection id "0HM88FRA6B207" completed keep alive response.
2021-04-26 08:45:13.563 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:45:13.565 +02:00 [INF] Request finished in 560.6355ms 200 application/javascript
2021-04-26 08:45:13.585 +02:00 [INF] Sending file. Request path: '/swagger-ui-standalone-preset.js'. Physical path: 'N/A'
2021-04-26 08:45:13.589 +02:00 [DBG] Connection id "0HM88FRA6B206" completed keep alive response.
2021-04-26 08:45:13.591 +02:00 [INF] Request finished in 56.7502ms 200 application/javascript
2021-04-26 08:45:13.859 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:8085/swagger/v1/swagger.json  
2021-04-26 08:45:13.862 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:45:13.863 +02:00 [DBG] The request path /swagger/v1/swagger.json does not match an existing file
2021-04-26 08:45:13.866 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:45:15.961 +02:00 [DBG] Connection id "0HM88FRA6B206" completed keep alive response.
2021-04-26 08:45:15.965 +02:00 [INF] Request finished in 2106.4632ms 200 application/json;charset=utf-8
2021-04-26 08:46:39.652 +02:00 [INF] Request starting HTTP/1.1 POST https://localhost:8085/v1/authormanagement/createuser?userId=Federico123&password=321&role=author application/json 91
2021-04-26 08:46:39.654 +02:00 [DBG] The host 'localhost' is excluded. Skipping HSTS header.
2021-04-26 08:46:39.657 +02:00 [DBG] POST requests are not supported
2021-04-26 08:46:39.662 +02:00 [DBG] AcceptLanguageHeaderRequestCultureProvider returned the following unsupported cultures '["en-US","en","es"]'.
2021-04-26 08:46:39.668 +02:00 [DBG] POST requests are not supported
2021-04-26 08:46:39.687 +02:00 [DBG] No candidates found for the request path '/v1/authormanagement/createuser'
2021-04-26 08:46:39.690 +02:00 [DBG] Request did not match any endpoints
2021-04-26 08:46:39.818 +02:00 [DBG] AuthenticationScheme: Bearer was not authenticated.
2021-04-26 08:46:39.885 +02:00 [DBG] Request successfully matched the route with name 'null' and template 'v1/authormanagement/createuser'
2021-04-26 08:46:40.009 +02:00 [INF] Route matched with {action = "CreateUser", controller = "Author"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] CreateUser(System.String, System.String, System.String, Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto) on controller Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Controllers.AuthorController (Devon4Net.WebAPI.Implementation).
2021-04-26 08:46:40.024 +02:00 [DBG] Execution plan of authorization filters (in the following order): ["Microsoft.AspNetCore.Mvc.Cors.CorsAuthorizationFilter (Order: -2147483548)"]
2021-04-26 08:46:40.033 +02:00 [DBG] Execution plan of resource filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter"]
2021-04-26 08:46:40.045 +02:00 [DBG] Execution plan of action filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)","Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)"]
2021-04-26 08:46:40.054 +02:00 [DBG] Execution plan of exception filters (in the following order): ["None"]
2021-04-26 08:46:40.057 +02:00 [DBG] Execution plan of result filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter","Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)"]
2021-04-26 08:46:40.066 +02:00 [DBG] The request has an origin header: 'https://localhost:8085'.
2021-04-26 08:46:40.069 +02:00 [INF] CORS policy execution successful.
2021-04-26 08:46:40.073 +02:00 [DBG] Executing controller factory for controller Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Controllers.AuthorController (Devon4Net.WebAPI.Implementation)
2021-04-26 08:46:40.531 +02:00 [DBG] An 'IServiceProvider' was created for internal use by Entity Framework.
2021-04-26 08:46:40.652 +02:00 [DBG] Executed controller factory for controller Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Controllers.AuthorController (Devon4Net.WebAPI.Implementation)
2021-04-26 08:46:40.712 +02:00 [DBG] Attempting to bind parameter 'userId' of type 'System.String' ...
2021-04-26 08:46:40.737 +02:00 [DBG] Attempting to bind parameter 'userId' of type 'System.String' using the name 'userId' in request data ...
2021-04-26 08:46:40.741 +02:00 [DBG] Done attempting to bind parameter 'userId' of type 'System.String'.
2021-04-26 08:46:40.745 +02:00 [DBG] Done attempting to bind parameter 'userId' of type 'System.String'.
2021-04-26 08:46:40.747 +02:00 [DBG] Attempting to validate the bound parameter 'userId' of type 'System.String' ...
2021-04-26 08:46:40.755 +02:00 [DBG] Done attempting to validate the bound parameter 'userId' of type 'System.String'.
2021-04-26 08:46:40.761 +02:00 [DBG] Attempting to bind parameter 'password' of type 'System.String' ...
2021-04-26 08:46:40.764 +02:00 [DBG] Attempting to bind parameter 'password' of type 'System.String' using the name 'password' in request data ...
2021-04-26 08:46:40.768 +02:00 [DBG] Done attempting to bind parameter 'password' of type 'System.String'.
2021-04-26 08:46:40.770 +02:00 [DBG] Done attempting to bind parameter 'password' of type 'System.String'.
2021-04-26 08:46:40.772 +02:00 [DBG] Attempting to validate the bound parameter 'password' of type 'System.String' ...
2021-04-26 08:46:40.774 +02:00 [DBG] Done attempting to validate the bound parameter 'password' of type 'System.String'.
2021-04-26 08:46:40.778 +02:00 [DBG] Attempting to bind parameter 'role' of type 'System.String' ...
2021-04-26 08:46:40.781 +02:00 [DBG] Attempting to bind parameter 'role' of type 'System.String' using the name 'role' in request data ...
2021-04-26 08:46:40.784 +02:00 [DBG] Done attempting to bind parameter 'role' of type 'System.String'.
2021-04-26 08:46:40.786 +02:00 [DBG] Done attempting to bind parameter 'role' of type 'System.String'.
2021-04-26 08:46:40.789 +02:00 [DBG] Attempting to validate the bound parameter 'role' of type 'System.String' ...
2021-04-26 08:46:40.792 +02:00 [DBG] Done attempting to validate the bound parameter 'role' of type 'System.String'.
2021-04-26 08:46:40.796 +02:00 [DBG] Attempting to bind parameter 'author' of type 'Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto' ...
2021-04-26 08:46:40.801 +02:00 [DBG] Attempting to bind parameter 'author' of type 'Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto' using the name '' in request data ...
2021-04-26 08:46:40.805 +02:00 [DBG] Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter' for content type 'application/json'.
2021-04-26 08:46:40.824 +02:00 [DBG] Connection id "0HM88FRA6B206", Request id "0HM88FRA6B206:00000005": started reading request body.
2021-04-26 08:46:40.828 +02:00 [DBG] Connection id "0HM88FRA6B206", Request id "0HM88FRA6B206:00000005": done reading request body.
2021-04-26 08:46:40.843 +02:00 [DBG] JSON input formatter succeeded, deserializing to type 'Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto'
2021-04-26 08:46:40.847 +02:00 [DBG] Done attempting to bind parameter 'author' of type 'Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto'.
2021-04-26 08:46:40.850 +02:00 [DBG] Done attempting to bind parameter 'author' of type 'Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto'.
2021-04-26 08:46:40.852 +02:00 [DBG] Attempting to validate the bound parameter 'author' of type 'Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto' ...
2021-04-26 08:46:40.874 +02:00 [DBG] Done attempting to validate the bound parameter 'author' of type 'Devon4Net.WebAPI.Implementation.Business.AuthorManagement.Dto.AuthorDto'.
2021-04-26 08:46:40.884 +02:00 [DBG] Executing method CreateUser from class AuthorController with values : userId = Federico123, password = 321, role = author
2021-04-26 08:46:40.891 +02:00 [DBG] Executing method CreateUser from class AuthorService with values : userId = Federico123, password = 321, role = author
2021-04-26 08:46:40.894 +02:00 [DBG] Create Todo method from repository AuthorRepository with value : Federico
2021-04-26 08:46:43.199 +02:00 [INF] Entity Framework Core 3.1.13 initialized 'AlejandriaContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: None
2021-04-26 08:46:43.303 +02:00 [DBG] 'AlejandriaContext' generated a value for the 'Id' property of new 'Author' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
2021-04-26 08:46:43.429 +02:00 [DBG] Context 'AlejandriaContext' started tracking 'Author' entity. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see key values.
2021-04-26 08:46:43.446 +02:00 [DBG] SaveChanges starting for 'AlejandriaContext'.
2021-04-26 08:46:43.457 +02:00 [DBG] DetectChanges starting for 'AlejandriaContext'.
2021-04-26 08:46:43.484 +02:00 [DBG] DetectChanges completed for 'AlejandriaContext'.
2021-04-26 08:46:43.572 +02:00 [DBG] Opening connection to database 'postgres' on server 'tcp://localhost:5432'.
2021-04-26 08:46:47.847 +02:00 [ERR] An error occurred using the connection to database 'postgres' on server 'tcp://localhost:5432'.
2021-04-26 08:46:47.922 +02:00 [INF] A transient exception has been encountered during execution and the operation will be retried after 0ms.
Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:5432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout(Task task, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:5432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout(Task task, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
2021-04-26 08:46:47.965 +02:00 [DBG] Opening connection to database 'postgres' on server 'tcp://localhost:5432'.
2021-04-26 08:46:48.403 +02:00 [DBG] Connection id "0HM88FRA6B207" received FIN.
2021-04-26 08:46:48.408 +02:00 [DBG] Connection id "0HM88FRA6B207" disconnecting.
2021-04-26 08:46:48.411 +02:00 [DBG] Connection id "0HM88FRA6B207" sending FIN because: "The client closed the connection."
2021-04-26 08:46:48.417 +02:00 [DBG] Connection id "0HM88FRA6B207" stopped.
2021-04-26 08:46:52.056 +02:00 [ERR] An error occurred using the connection to database 'postgres' on server 'tcp://localhost:5432'.
2021-04-26 08:46:52.074 +02:00 [INF] A transient exception has been encountered during execution and the operation will be retried after 1011ms.
Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:5432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout(Task task, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:5432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout(Task task, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
2021-04-26 08:46:53.122 +02:00 [DBG] Opening connection to database 'postgres' on server 'tcp://localhost:5432'.
2021-04-26 08:46:57.241 +02:00 [ERR] An error occurred using the connection to database 'postgres' on server 'tcp://localhost:5432'.
2021-04-26 08:46:57.271 +02:00 [INF] A transient exception has been encountered during execution and the operation will be retried after 3122ms.
Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:5432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout(Task task, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:5432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout(Task task, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
2021-04-26 08:47:00.563 +02:00 [DBG] Opening connection to database 'postgres' on server 'tcp://localhost:5432'.
2021-04-26 08:47:04.678 +02:00 [ERR] An error occurred using the connection to database 'postgres' on server 'tcp://localhost:5432'.
2021-04-26 08:47:04.709 +02:00 [INF] A transient exception has been encountered during execution and the operation will be retried after 7528ms.
Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:5432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout(Task task, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:5432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout(Task task, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
2021-04-26 08:47:06.159 +02:00 [INF] Application is shutting down...
2021-04-26 08:47:06.162 +02:00 [DBG] Hosting stopping
